[supervisord]
nodaemon=true

[program:deeplx]
command=/app/DeepLX --port 1188
directory=/app
autostart=true
autorestart=true

[program:streamlit]
command=streamlit run app.py --server.port=10000 --server.address=0.0.0.0
directory=/app
autostart=true
autorestart=true
